In [1]:
from selenium import webdriver
import time
import pandas as pd

In [2]:
data = pd.DataFrame(columns=['Date','Asset','Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'])
etfs = ['VTI','VXUS','BND','BNDX']

In [3]:
options = webdriver.ChromeOptions()
options.add_argument('--headless')

for etf in etfs:
    asset = etf
    url = 'https://finance.yahoo.com/quote/'+asset+'/history'
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    driver.find_element_by_xpath("//div[@class='Pos(r) D(ib) C($linkColor) O(n):f Cur(p)']//*[name()='svg']").click()
    driver.find_element_by_xpath("//div[@class='W(195px)']//ul[2]//li[4]//button[@class = 'Py(5px) W(45px) Fz(s) C($tertiaryColor) Cur(p) Bd Bdc($seperatorColor) Bgc($lv4BgColor) Bdc($linkColor):h Bdrs(3px)']").click()
    driver.find_element_by_xpath("//div[@class='Bgc($lv1BgColor) Bdrs(3px) P(10px)']//button[1]").click()
    x = driver.find_element_by_xpath("//div[@class='C($tertiaryColor) Mt(20px) Mb(15px)']//a[1]").get_attribute('href')
    driver.close()
    df = pd.read_csv(x)
    df['Asset'] = asset
    data = data.append(df)
    print(asset)

VTI
VXUS
BND
BNDX

In [9]:
data['Date'] = pd.to_datetime(data['Date'])

In [10]:
data.dtypes

Date         datetime64[ns]
Asset                object
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume               object
dtype: object

In [21]:
data[data.Date > '2010-01-01']

,Date,Asset,Open,High,Low,Close,Adj Close,Volume
2149,2010-01-04,VTI,56.860001,57.380001,56.840000,57.310001,47.202740,2251500
2150,2010-01-05,VTI,57.340000,57.540001,57.110001,57.529999,47.383919,1597700
2151,2010-01-06,VTI,57.500000,57.720001,57.410000,57.610001,47.449802,2120300
2152,2010-01-07,VTI,57.549999,57.889999,57.290001,57.849998,47.647484,1656700
2153,2010-01-08,VTI,57.700001,58.049999,57.560001,58.040001,47.803974,1650000
...,...,...,...,...,...,...,...,...
1705,2020-03-12,BNDX,57.799999,57.990002,56.680000,56.720001,56.720001,11961600
1706,2020-03-13,BNDX,56.709999,56.860001,56.330002,56.700001,56.700001,6033300
1707,2020-03-16,BNDX,56.049999,56.820000,55.810001,56.220001,56.220001,4139700
1708,2020-03-17,BNDX,55.919998,56.360001,55.660000,56.250000,56.250000,3814400
1709,2020-03-18,BNDX,55.139999,55.500000,54.520000,54.959999,54.959999,4179100